// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mwyp_3ngYd60R8StZeOsc4b9icHp2YQ',
    appId: '1:523566725208:web:3cc9487268646ace40b22d',
    messagingSenderId: '523566725208',
    projectId: 'navigation-3eb77',
    authDomain: 'navigation-3eb77.firebaseapp.com',
    storageBucket: 'navigation-3eb77.firebasestorage.app',
    measurementId: 'G-KNXM89MJ4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ts6CvNr1NFKQ3CLg-S3c0mnBxo1tuo',
    appId: '1:523566725208:android:90e9b0cd7b1eea9240b22d',
    messagingSenderId: '523566725208',
    projectId: 'navigation-3eb77',
    storageBucket: 'navigation-3eb77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYuDJM06P7wTB-qF_QDIXmCD9Py4eGrg',
    appId: '1:523566725208:ios:9867d213b84d444f40b22d',
    messagingSenderId: '523566725208',
    projectId: 'navigation-3eb77',
    storageBucket: 'navigation-3eb77.firebasestorage.app',
    iosBundleId: 'com.example.taleTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKYuDJM06P7wTB-qF_QDIXmCD9Py4eGrg',
    appId: '1:523566725208:ios:9867d213b84d444f40b22d',
    messagingSenderId: '523566725208',
    projectId: 'navigation-3eb77',
    storageBucket: 'navigation-3eb77.firebasestorage.app',
    iosBundleId: 'com.example.taleTrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8mwyp_3ngYd60R8StZeOsc4b9icHp2YQ',
    appId: '1:523566725208:web:ba4574785d677bcd40b22d',
    messagingSenderId: '523566725208',
    projectId: 'navigation-3eb77',
    authDomain: 'navigation-3eb77.firebaseapp.com',
    storageBucket: 'navigation-3eb77.firebasestorage.app',
    measurementId: 'G-RYK0Q4HCV2',
  );

}