// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYD7SrY3qbWoRYKIoq4xRcpVFgCV25xKw',
    appId: '1:650008545794:web:1a7ba6d375fa4e8767751b',
    messagingSenderId: '650008545794',
    projectId: 'tale-trace-app',
    authDomain: 'tale-trace-app.firebaseapp.com',
    storageBucket: 'tale-trace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FNH6WfZ3GLNDhigDKjULcDRZUhmaTs8',
    appId: '1:650008545794:android:9fd195f2265148f067751b',
    messagingSenderId: '650008545794',
    projectId: 'tale-trace-app',
    storageBucket: 'tale-trace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSmgaSDp_5NMjd9iL5ssjmS5LRWPWMf8w',
    appId: '1:650008545794:ios:9a1e935a8acf6fc467751b',
    messagingSenderId: '650008545794',
    projectId: 'tale-trace-app',
    storageBucket: 'tale-trace-app.firebasestorage.app',
    iosBundleId: 'com.example.taleTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSmgaSDp_5NMjd9iL5ssjmS5LRWPWMf8w',
    appId: '1:650008545794:ios:9a1e935a8acf6fc467751b',
    messagingSenderId: '650008545794',
    projectId: 'tale-trace-app',
    storageBucket: 'tale-trace-app.firebasestorage.app',
    iosBundleId: 'com.example.taleTrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHRS0mMG25NZX_zuHM1al_ZYUuAaY1fy0',
    appId: '1:650008545794:web:5c9fee7f3ac630ba67751b',
    messagingSenderId: '650008545794',
    projectId: 'tale-trace-app',
    authDomain: 'tale-trace-app.firebaseapp.com',
    storageBucket: 'tale-trace-app.firebasestorage.app',
  );
}
